### ISSUE TITLE
[AAV] indentificateurs 

### ISSUE THREAD

**Issue by plgitlogin** [PremierLangage/ap1-19-20#3]
reconnaitre les identificateurs corrects des invalides.

**Comment by niotie** [comment]
je pense que cette issue devrait porter sur un autre dépôt

**Comment by nimdanor** [comment]
Pourquoi pas ici tu veux séparer les templates et outils des exercices et ressources.
Dans l'approche actuelle il y a pour chaque cercle (je pense ici au cercle "python") deux répertoires tools et published  qui pour moi peuvent être dans le meme repo.
