### ISSUE TITLE
Ajout d'une fonction de Taboo

### ISSUE THREAD

**Issue by ochampal** [PremierLangage/ap1-19-20#9]
Objectif : définir des exercices interdisant l'usage de certains mots notamment (for ou while). Le but permettre aux étudiants de prendre des bons réflexes de programmation

**Comment by nimdanor** [comment]
C'est fait dans 
Yggdrasil/ComputerScience/python/AP1-1920/templates/utils/pltestgrader.py
pour les autres graders il suffit de faire une copie de la fonction  checktaboo
et des deux lignes dans le main.

**Comment by niotie** [comment]
Oui, on peut s'inspirer de ce que tu as fait dans pltest, mais ce serait bien de l'intégrer un peu proprement dans le système d'assertions de generic.

Quand j'aurai un peu de temps (pas maintenant donc), j'aimerais bien voir ce qu'on pourrait faire avec le module [ast](https://docs.python.org/3/library/ast.html).

**Comment by niotie** [comment]
Il existe maintenant une fonction `assert_no_loop` dans le grader. Elle permet de vérifier l'absence de boucle `for` (y compris mutations de listes), `while` ou les deux (par défaut).
